# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44e072329482721ac9527ee0dc7a494160de84bef7a83ae2f6a1552181d0805adb7d2405b8b585e73d344e080487343f12ddffb3ad242494cf3cfa27b53541f0

test:
  secret_key_base: 5540d267e59176e87fe27ebd485b6fbd8fc8496975d2351b0497e477236448b2506bb4a41ec120538a4231ce0612182adba4d0940a30525198f653a7a2f3ab0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
